### ISSUE TITLE
다시 시작 시, 공 발사 안 됨

### ISSUE THREAD

**Issue by rlarhdal** [rlarhdal/BrickOut#2]
![1](https://github.com/rlarhdal/BrickOut/assets/93560053/1ec35aa3-1bd7-4eb6-808c-ce9a673dafa7)
![2](https://github.com/rlarhdal/BrickOut/assets/93560053/32e21a1c-db4e-4833-8b18-5aa7f5f2a6a4)

게임 다시 시작 시, 공 발사 및 패들 움직임 없음

**Comment by rlarhdal** [comment]
1번 이슈와 같은 로직으로 해결했습니다.

**Comment by fusil5577** [comment]
![image](https://github.com/rlarhdal/BrickOut/assets/167050340/e43648df-5a24-42d7-a468-4537a253dbac)

패배시 공이 없어지기 때문에 만약에 공이 하나도 없다면 하나 생성해줍니다.
시간도 정상적으로 가도록 해줬습니다.

**Comment by fusil5577** [comment]
![image](https://github.com/rlarhdal/BrickOut/assets/167050340/c4cef9f7-2e6e-4c66-a11c-89f22f53af31)

![image](https://github.com/rlarhdal/BrickOut/assets/167050340/09ebd603-f447-4b21-9c3e-bce0d2f9c07b)

Scene을 로드하는 스크립트에서 추가하는게 좀 별로여서 근본적인 원인인 Ball이 프리팹으로서 GameScene이 열릴때마다 생성되는게 아닌 GameScene에 하나가 처음에 배치되어 있어서 프리팹으로 바꿔주고 GameManager가 GameScene이 열릴때마다 소환해주는 방식으로 바꿨습니다.
